services:
  - type: web
    name: KIITBites
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: MONGO_URI_USER
        sync: false
      - key: MONGO_URI_ITEM
        sync: false
      - key: MONGO_URI_ORDER
        sync: false
      - key: MONGO_URI_INVENTORY
        sync: false
      - key: MONGO_URI_FOODCOURT
        sync: false
      - key: MONGO_URI_CACHE
        sync: false
